@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Ana Claudia Nogueira",
    "email": "anacnogueira@gmail.com",
    "password": "123456"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "anacnogueira2@gmail.com",
    "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}